<?xml version="1.0"?>
<robot name="home_robot" xmlns:xacro="http://ros.org/wiki/xacro">
 <xacro:include filename="$(find robot_description)/urdf/common_properties.xacro"/>
 <xacro:include filename="$(find robot_description)/urdf/OS1-32.urdf.xacro"/> 
<xacro:macro name ="home_robot_platform">
 <!-- Robot dimensions --> 
  <xacro:property name="base_length" value="0.53" />
  <xacro:property name="base_width" value="0.56" />
  <xacro:property name="base_height" value="0.07" />
  <xacro:property name="wheel_diam" value="0.04" />
  <xacro:property name="wheel_width" value="0.03" />
  <xacro:property name="platform1_elevation" value="0.83" />
  <xacro:property name="platform2_elevation" value="1.0" />
  <xacro:property name="column_diam" value="0.04" />
  <xacro:property name="platform1_length" value="0.35" />
  <xacro:property name="platform1_width" value="0.40" />
  <xacro:property name="platform2_length" value="0.3" />
  <xacro:property name="platform2_width" value="0.35" />
  <xacro:property name="platform_height" value="0.02" />
  <xacro:property name="platform1_elevation" value="0.71" />
  <xacro:property name="platform2_elevation" value="0.87" />
  <xacro:property name="pi" value="3.1415926535897931" />

<!-- Macro to define wheels at back  -->
  <xacro:macro name="wheel_back" params="suffix reflect">

  <joint name="wheel_back_${suffix}_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_back_${suffix}_link"/>
    <axis xyz="0 0 1"/>
    <origin xyz="${-base_length/2} ${-base_width/2*reflect} ${wheel_diam/2 - base_height}" rpy="${-pi/2} 0 0"/>
  </joint>

  <link name="wheel_back_${suffix}_link">
    <visual>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_diam/2}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <material name="dark"/>
    </visual>
 
   <collision>
<!--   
   <origin xyz="-0.064 0 0.047" rpy="0 0 0"/>
 -->
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_diam/2}"/>
      </geometry>
    </collision>

    <inertial>
 <!-- Center of mass origin -->
    <origin xyz="0 0 0"/>

      <mass value="3.4"/>
      <inertia ixx="0.0067" ixy="-0" ixz="0"
               iyy="0.0123" iyz="0"
               izz="0.0067" />
    </inertial>

  </link>

  </xacro:macro>

<!-- Macro to define wheels at front  -->
  <xacro:macro name="wheel_front" params="suffix reflect">

  <joint name="wheel_front_${suffix}_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_front_${suffix}_link"/>
    <axis xyz="0 0 1"/>
    <origin xyz="${base_length/2} ${-base_width/2*reflect} ${wheel_diam/2 - base_height}" rpy="${-pi/2} 0 0"/>
  </joint>

  <link name="wheel_front_${suffix}_link">
    <visual>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_diam/2}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <material name="dark"/>
    </visual>
 
   <collision>
<!--   
   <origin xyz="-0.064 0 0.047" rpy="0 0 0"/>
 -->
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_diam/2}"/>
      </geometry>
    </collision>

    <inertial>
 <!-- Center of mass origin -->
    <origin xyz="0 0 0"/>

      <mass value="3.4"/>
      <inertia ixx="0.0067" ixy="-0" ixz="0"
               iyy="0.0123" iyz="0"
               izz="0.0067" />
    </inertial>

  </link>

  </xacro:macro>

<!-- Platforms column macro -->
  <joint name="platform_column_joint" type="fixed">
    <parent link="base_link"/>
    <child link="platform_column_link"/>
    <origin xyz="0.07 0 0.22"/>
  </joint>
 <link name="platform_column_link">
    <visual>
      <geometry>
          <cylinder length="${(platform2_elevation/2)+0.02}" radius="${column_diam/2}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <material name="dark"/>
    </visual>
   <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="${platform2_elevation-base_height}" radius="${column_diam}"/>
      </geometry>
   </collision>
   <inertial>

    <origin xyz="0 0 0" rpy="0 0 0"/>

      <mass value="1.25"/>
      <inertia ixx="0.045453" ixy="0" ixz="0"
               iyy="0.049627" iyz="0"
               izz="0.004174" />
    </inertial>

  </link>>
 
<!-- Platform dimensions -->
    <link name="base_link">
    <visual>
      <origin xyz="0 0 0"/>
      <geometry>
          <box size ="${base_length} ${base_width} ${base_height/2}"/>
      </geometry>
      <material name="light_black" />
    </visual>
   <collision>
      <origin xyz="0 0 0"/>
      <geometry>
        <box size ="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>

</link>

<!-- Upper platform -->
<joint name="platform2_joint" type="fixed">
	<parent link="base_link"/>
	<child link="platform2_link"/>
        <origin xyz="${base_length/2-platform2_width/2} 0 ${(base_height + platform2_elevation)/2}"/>
</joint>

    <link name="platform2_link">
    <visual>
	<origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size ="${platform2_length} ${platform2_width} ${platform_height}"/>
      </geometry>
      <material name="light_black" />
    </visual>
   <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size ="${platform2_length} ${platform2_width} ${platform_height}"/>
      </geometry>
    </collision>

    <inertial>
 
    <origin xyz="0 0 0" rpy="0 0 0"/>

      <mass value="3.12"/>
      <inertia ixx="0.065" ixy="0" ixz="0"
               iyy="0.0816" iyz="0"
               izz="0.147" />
    </inertial>  

</link>

<!-- Lower platform -->
<joint name="platform1_joint" type="fixed">
	<parent link="base_link"/>
	<child link="platform1_link"/>
        <origin xyz="${base_length/2} 0 ${(base_height + platform1_elevation)/2}"/>
</joint>

    <link name="platform1_link">
    <visual>
        <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size ="${platform1_length} ${platform1_width} ${platform_height}"/>
      </geometry>
      <material name="light_black" />
    </visual>
   <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size ="${platform1_length} ${platform1_width} ${platform_height}"/>
      </geometry>
    </collision>

    <inertial>
 
    <origin xyz="0 0 0" rpy="0 0 0"/>

      <mass value="2.52"/>
      <inertia ixx="0.065" ixy="0" ixz="0"
               iyy="0.0816" iyz="0"
               izz="0.147" />
    </inertial>  

</link>

<!-- Sensors -->

<xacro:IG1 parent="base_link" name="IMU" topic="/imu/data">
    <origin xyz="${(base_length/2)+0.095} -0.025 ${((base_height + platform1_elevation)/2)+0.072}" rpy="0 0 0" />
</xacro:IG1>

<xacro:OS1-32 parent="base_link" name="os1_sensor" topic_points="/os1_cloud_node/points" topic_imu="/os1_cloud_node/imu">
    <origin xyz="${(base_length/2)+0.1} 0 ${((base_height + platform1_elevation)/2)+0.045}" rpy="0 0 0" />
</xacro:OS1-32>

<!-- Wheels -->
 <xacro:wheel_back suffix="left" reflect ="1"/>
 <xacro:wheel_back suffix="right" reflect ="-1"/>
 <xacro:wheel_front suffix="left" reflect="1"/>
 <xacro:wheel_front suffix="right" reflect="-1"/>

</xacro:macro>

<xacro:macro name="IG1" params="*origin parent:=base_link topic:=/imu/data name:=IMU">
    <joint name="${name}_sensor_joint" type="fixed">
        <xacro:insert_block name="origin" />
        <parent link="${parent}"/>
        <child link="${name}_sensor_link"/>
    </joint>
     
    <link name="${name}_sensor_link">
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.051 0.045 0.024"/>
            </geometry>
        </collision>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                        <mesh filename="package://robot_description/meshes/sensors/IG1.stl" /> 
            <!-- box size="0.051 0.045 0.024"/>-->
            </geometry>
            <material name="dark"/>
        </visual>
        <inertial>
            <mass value="0.001" />
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="0.00000015" ixy="0" ixz="0" iyy="0.00000015" iyz="0" izz="0.00000015" />
        </inertial>
    </link>
    
</xacro:macro>

<xacro:home_robot_platform />
</robot>
